Update pipelines

diff --git a/.github/workflows/basePipeline.yml b/.github/workflows/basePipeline.yml
--- a/.github/workflows/basePipeline.yml
+++ b/.github/workflows/basePipeline.yml
@@ -112,13 +112,12 @@ jobs:
           github_token: ${{ secrets.GITHUB_TOKEN }}
           publish_branch: gh-pages
           publish_dir: ./gh-pages
-          destination_dir: ${{ github.run_number }}
 
       - name: Construct Report Path
         id: construct-path
         run: |
-          echo "report-path=${{ steps.allure-report.outputs.reports-site-path }}/${{ github.run_number }}" >> $GITHUB_OUTPUT
-          echo "REPORT_PATH=${{ steps.allure-report.outputs.reports-site-path }}/${{ github.run_number }}" >> $GITHUB_ENV
+          echo "report-path=${{ steps.allure-report.outputs.reports-site-path }}" >> $GITHUB_OUTPUT
+          echo "REPORT_PATH=${{ steps.allure-report.outputs.reports-site-path }}" >> $GITHUB_ENV
 
       - name: Publish Allure report link
         if: ${{ always() && steps.allure-report.outcome == 'success' }}
@@ -166,7 +165,7 @@ jobs:
         run: |
           set -e
 
-          SUMMARY=$(jq -e '{total: .statistic.total, passed: .statistic.passed, failed: .statistic.failed, skipped: .statistic.skipped, broken: .statistic.broken, unknown: .statistic.unknown, duration: .time.duration | tostring}' ./gh-pages/${{ env.REPORT_PATH }}/widgets/summary.json || echo '{}')
+          SUMMARY=$(jq -e '{total: .statistic.total, passed: .statistic.passed, failed: .statistic.failed, skipped: .statistic.skipped, broken: .statistic.broken, unknown: .statistic.unknown, duration: .time.duration | tostring}' ./downloaded-artifacts/widgets/summary.json || echo '{}')
 
           DURATION_MS=$(echo $SUMMARY | jq -r .duration)
           DURATION=$((DURATION_MS / 1000))
@@ -200,8 +199,8 @@ jobs:
           echo "PASS_RATE=$PASS_RATE" >> $GITHUB_ENV
 
           if [ "$FAILED" -gt 0 ]; then
-            FAILED_TESTS=$(jq -e '[.. | select(.name? | type == "string" and contains(".")) | {test: .name, test_cases: [.children[]? | select(.status == "failed") | .name]}] | map(select(.test_cases | length > 0))' ./target/allure-report/data/suites.json || echo '[]')
-            jq -e '[.. | select(.name? | type == "string" and contains(".")) | {error_message: .name, "test_case": ([.children[]?.name])}]' ./target/allure-report/data/categories.json > failed_messages.json || echo '[]' > failed_messages.json
+            FAILED_TESTS=$(jq -e '[.. | select(.name? | type == "string" and contains(".")) | {test: .name, test_cases: [.children[]? | select(.status == "failed") | .name]}] | map(select(.test_cases | length > 0))' ./downloaded-artifacts/data/suites.json || echo '[]')
+            jq -e '[.. | select(.name? | type == "string" and contains(".")) | {error_message: .name, "test_case": ([.children[]?.name])}]' ./downloaded-artifacts/data/categories.json > failed_messages.json || echo '[]' > failed_messages.json
             echo "HAS_FAILED_TESTS=true" >> $GITHUB_ENV
             echo "FAILED_TESTS=$(echo "$FAILED_TESTS" | jq -c .)" >> $GITHUB_ENV
           else
